language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=Django==1.4.19
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.10
  - DJANGO=Django==1.7.4
  - DJANGO=https://www.djangoproject.com/download/1.8a1/tarball/
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test test_app
  - coverage run --source=django_bootstrap3_form,testproject/test_app testproject/manage.py test test_app
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.4
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.8a1/tarball/
    - python: 3.3
      env: DJANGO=Django==1.4.19
    - python: 3.4
      env: DJANGO=Django==1.4.19
