language: python
dist: bionic
matrix:
  include:
    - python: 3.7
      env: DJANGO="Django==2.2.14"
    - python: 3.8
      env: DJANGO="Django==3.0.8"
    - python: 3.8
      env: DJANGO="Django==3.1b1"
install:
  - pip install $DJANGO
  - pip install -U -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python -Wd testproject/manage.py test test_app
  - coverage run --source=django_bootstrap3_form,testproject/test_app testproject/manage.py test test_app
  - coverage report
after_success:
  - coveralls
