language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO=Django==1.8.17
  - DJANGO=Django==1.9.12
  - DJANGO=Django==1.10.4
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - pip install -e .
script:
  - python testproject/manage.py test test_app
  - coverage run --source=django_bootstrap3_form,testproject/test_app testproject/manage.py test test_app
  - coverage report
after_success:
  - coveralls
