language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=Django==1.4.13
  - DJANGO=Django==1.5.7
  - DJANGO=Django==1.6.5
  - DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7b4.tar.gz
install:
  - pip install $DJANGO
  - pip install -r testproject/requirements_test.txt
  - pip install -r testproject/requirements_travis.txt
  - python setup.py install
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
script:
  - cd testproject
  - python manage.py test test_app
  - coverage run --source=django_bootstrap3_form,test_app manage.py test test_app
  - coverage report
after_success:
  - coveralls
  - cd ..
  - covio
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/m/releases/1.7/Django-1.7b4.tar.gz
    - python: 3.3
      env: DJANGO=Django==1.4.13
    - python: 3.4
      env: DJANGO=Django==1.4.13
